In [2]:
import numpy as np
import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Dense, Flatten
from tensorflow.keras.utils import to_categorical

In [5]:
train_images = mnist.train_images()
train_labels = mnist.train_labels()
test_images = mnist.test_images()
test_labels = mnist.test_labels()

In [6]:
# Normalize the images.
train_images = (train_images / 255) - 0.5
test_images = (test_images / 255) - 0.5

# Reshape the images.
train_images = np.expand_dims(train_images, axis=3)
test_images = np.expand_dims(test_images, axis=3)

num_filters = 8
filter_size = 3
pool_size = 2

# Build the model.
model = Sequential([
  Conv2D(num_filters, filter_size, input_shape=(28, 28, 1)),
  MaxPooling2D(pool_size=pool_size),
  Flatten(),
  Dense(10, activation='softmax'),
])

# Compile the model.
model.compile(
  'adam',
  loss='categorical_crossentropy',
  metrics=['accuracy'],
)

# Train the model.
model.fit(
  train_images,
  to_categorical(train_labels),
  epochs=3,
  validation_data=(test_images, to_categorical(test_labels)),
)

Epoch 1/3
1875/1875 [==============================] - 23s 11ms/step - loss: 0.3648 - accuracy: 0.8965 - val_loss: 0.2210 - val_accuracy: 0.9364
Epoch 2/3
1875/1875 [==============================] - 17s 9ms/step - loss: 0.1742 - accuracy: 0.9507 - val_loss: 0.1357 - val_accuracy: 0.9592
Epoch 3/3
1875/1875 [==============================] - 17s 9ms/step - loss: 0.1233 - accuracy: 0.9645 - val_loss: 0.1089 - val_accuracy: 0.9671


In [9]:
# TESTING #1
# Save the model to disk.
model.save_weights('cnn.h5')

# Load the model from disk later using:
# model.load_weights('cnn.h5')

# Predict on the first 5 test images.
predictions = model.predict(test_images[:5])

# Print our model's predictions.
print(np.argmax(predictions, axis=1)) # [7, 2, 1, 0, 4]

# Check our predictions against the ground truths.
print(test_labels[:5]) # [7, 2, 1, 0, 4]

[7 2 1 0 4]
[7 2 1 0 4]


# Recommended Experiments

## 1. Varying network depth

In [10]:
# Build the model.
model = Sequential([
  Conv2D(num_filters, filter_size, input_shape=(28, 28, 1)),
  Conv2D(num_filters, filter_size), #Layer added
  MaxPooling2D(pool_size=pool_size),
  Flatten(),
  Dense(10, activation='softmax'),
])

# Compile the model.
model.compile(
  'adam',
  loss='categorical_crossentropy',
  metrics=['accuracy'],
)

# Train the model.
model.fit(
  train_images,
  to_categorical(train_labels),
  epochs=3,
  validation_data=(test_images, to_categorical(test_labels)),
)

Epoch 1/3
1875/1875 [==============================] - 28s 14ms/step - loss: 0.2758 - accuracy: 0.9185 - val_loss: 0.1239 - val_accuracy: 0.9631
Epoch 2/3
1875/1875 [==============================] - 26s 14ms/step - loss: 0.1105 - accuracy: 0.9667 - val_loss: 0.0829 - val_accuracy: 0.9732
Epoch 3/3
1875/1875 [==============================] - 26s 14ms/step - loss: 0.0840 - accuracy: 0.9742 - val_loss: 0.0748 - val_accuracy: 0.9764


In [12]:
# Save the model to disk.
model.save_weights('cnn2.h5')

# Load the model from disk later using:
# model.load_weights('cnn.h5')

# Predict on the first 5 test images.
predictions = model.predict(test_images[:20])

# Print our model's predictions.
print(np.argmax(predictions, axis=1))

# Check our predictions against the ground truths.
print(test_labels[:20])

[7 2 1 0 4 1 4 9 6 9 0 6 9 0 1 5 9 7 3 4]
[7 2 1 0 4 1 4 9 5 9 0 6 9 0 1 5 9 7 3 4]


## 2. Adding Dropout layers

In [14]:
# Build the model.
model = Sequential([
  Conv2D(num_filters, filter_size, input_shape=(28, 28, 1)),
  MaxPooling2D(pool_size=pool_size),
  Dropout(0.5), #Dropout layer
  Flatten(),
  Dense(10, activation='softmax'),
])

# Compile the model.
model.compile(
  'adam',
  loss='categorical_crossentropy',
  metrics=['accuracy'],
)

# Train the model.
model.fit(
  train_images,
  to_categorical(train_labels),
  epochs=3,
  validation_data=(test_images, to_categorical(test_labels)),
)

NameError: name 'Dropout' is not defined

In [ ]:
# cnn4.h5

## 3. Adding Fully-connected Layers

In [15]:
# Build the model.
model = Sequential([
  Conv2D(num_filters, filter_size, input_shape=(28, 28, 1)),
  MaxPooling2D(pool_size=pool_size),
  Flatten(),
  Dense(64, activation='relu'), #Fully connected layer
  Dense(10, activation='softmax'),
])

# Compile the model.
model.compile(
  'adam',
  loss='categorical_crossentropy',
  metrics=['accuracy'],
)

# Train the model.
model.fit(
  train_images,
  to_categorical(train_labels),
  epochs=3,
  validation_data=(test_images, to_categorical(test_labels)),
)

Epoch 1/3
1875/1875 [==============================] - 21s 11ms/step - loss: 0.2710 - accuracy: 0.9196 - val_loss: 0.1324 - val_accuracy: 0.9605
Epoch 2/3
1875/1875 [==============================] - 20s 11ms/step - loss: 0.1026 - accuracy: 0.9690 - val_loss: 0.0790 - val_accuracy: 0.9769
Epoch 3/3
1875/1875 [==============================] - 20s 11ms/step - loss: 0.0683 - accuracy: 0.9792 - val_loss: 0.0689 - val_accuracy: 0.9782


In [16]:
# Save the model to disk.
model.save_weights('cnn4.h5')

# Load the model from disk later using:
# model.load_weights('cnn.h5')

# Predict on the first 5 test images.
predictions = model.predict(test_images[:20])

# Print our model's predictions.
print(np.argmax(predictions, axis=1))

# Check our predictions against the ground truths.
print(test_labels[:20])

[7 2 1 0 4 1 4 9 5 9 0 6 9 0 1 5 9 7 3 4]
[7 2 1 0 4 1 4 9 5 9 0 6 9 0 1 5 9 7 3 4]


## 4. Messing with convolution parameters 

In [17]:
# Build the model.
model = Sequential([
  Conv2D(
    num_filters,
    filter_size,
    input_shape=(28, 28, 1),
    strides=2,    padding='same',    activation='relu',  ), #Modified and added parameters
  MaxPooling2D(pool_size=pool_size),
  Flatten(),
  Dense(10, activation='softmax'),
])

# Compile the model.
model.compile(
  'adam',
  loss='categorical_crossentropy',
  metrics=['accuracy'],
)

# Train the model.
model.fit(
  train_images,
  to_categorical(train_labels),
  epochs=3,
  validation_data=(test_images, to_categorical(test_labels)),
)

Epoch 1/3
1875/1875 [==============================] - 14s 7ms/step - loss: 0.4573 - accuracy: 0.8768 - val_loss: 0.2127 - val_accuracy: 0.9374
Epoch 2/3
1875/1875 [==============================] - 12s 6ms/step - loss: 0.1933 - accuracy: 0.9424 - val_loss: 0.1611 - val_accuracy: 0.9517
Epoch 3/3
1875/1875 [==============================] - 11s 6ms/step - loss: 0.1574 - accuracy: 0.9525 - val_loss: 0.1436 - val_accuracy: 0.9587


In [18]:
# Save the model to disk.
model.save_weights('cnn2.h5')

# Load the model from disk later using:
# model.load_weights('cnn.h5')

# Predict on the first 5 test images.
predictions = model.predict(test_images[:20])

# Print our model's predictions.
print(np.argmax(predictions, axis=1))

# Check our predictions against the ground truths.
print(test_labels[:20])

[7 2 1 0 4 1 4 9 6 9 0 6 9 0 1 5 9 7 3 4]
[7 2 1 0 4 1 4 9 5 9 0 6 9 0 1 5 9 7 3 4]


# Personal experiments

In [19]:
# Build the model.
model = Sequential([
  Conv2D(
    num_filters,
    filter_size,
    input_shape=(28, 28, 1),
    strides=2,    padding='same',    activation='relu',  ), #Modified and added parameters
  Conv2D(num_filters, filter_size), #Layer added
    MaxPooling2D(pool_size=pool_size),
  Flatten(),
  Dense(64, activation='relu'), #Fully connected layer
  Dense(10, activation='softmax'),
])

# Compile the model.
model.compile(
  'adam',
  loss='categorical_crossentropy',
  metrics=['accuracy'],
)

# Train the model.
model.fit(
  train_images,
  to_categorical(train_labels),
  epochs=3,
  validation_data=(test_images, to_categorical(test_labels)),
)

Epoch 1/3
1875/1875 [==============================] - 17s 9ms/step - loss: 0.2645 - accuracy: 0.9210 - val_loss: 0.0984 - val_accuracy: 0.9697
Epoch 2/3
1875/1875 [==============================] - 15s 8ms/step - loss: 0.0831 - accuracy: 0.9746 - val_loss: 0.0662 - val_accuracy: 0.9794
Epoch 3/3
1875/1875 [==============================] - 15s 8ms/step - loss: 0.0579 - accuracy: 0.9819 - val_loss: 0.0590 - val_accuracy: 0.9800


In [21]:
# Save the model to disk.
model.save_weights('cnn5.h5')

# Load the model from disk later using:
# model.load_weights('cnn.h5')

# Predict on the first 5 test images.
predictions = model.predict(test_images[:20])

# Print our model's predictions.
print(np.argmax(predictions, axis=1))

# Check our predictions against the ground truths.
print(test_labels[:20])

[7 2 1 0 4 1 4 9 5 9 0 6 9 0 1 5 9 7 8 4]
[7 2 1 0 4 1 4 9 5 9 0 6 9 0 1 5 9 7 3 4]
