In [3]:
import numpy as np
import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Dense, Flatten, Dropout
from tensorflow.keras.utils import to_categorical

In [4]:
train_images = mnist.train_images()
train_labels = mnist.train_labels()
test_images = mnist.test_images()
test_labels = mnist.test_labels()

In [5]:
# Normalize the images.
train_images = (train_images / 255) - 0.5
test_images = (test_images / 255) - 0.5

# Reshape the images.
train_images = np.expand_dims(train_images, axis=3)
test_images = np.expand_dims(test_images, axis=3)

num_filters = 8
filter_size = 3
pool_size = 2

# Build the model.
model = Sequential([
  Conv2D(num_filters, filter_size, input_shape=(28, 28, 1)),
  MaxPooling2D(pool_size=pool_size),
  Flatten(),
  Dense(10, activation='softmax'),
])

# Compile the model.
model.compile(
  'adam',
  loss='categorical_crossentropy',
  metrics=['accuracy'],
)

# Train the model.
model.fit(
  train_images,
  to_categorical(train_labels),
  epochs=3,
  validation_data=(test_images, to_categorical(test_labels)),
)

Epoch 1/3
1875/1875 [==============================] - 25s 13ms/step - loss: 0.3721 - accuracy: 0.8937 - val_loss: 0.2163 - val_accuracy: 0.9361
Epoch 2/3
1875/1875 [==============================] - 18s 10ms/step - loss: 0.1888 - accuracy: 0.9451 - val_loss: 0.1475 - val_accuracy: 0.9572
Epoch 3/3
1875/1875 [==============================] - 20s 10ms/step - loss: 0.1374 - accuracy: 0.9611 - val_loss: 0.1215 - val_accuracy: 0.9626


In [6]:
# TESTING #1
# Save the model to disk.
model.save_weights('cnn.h5')

# Load the model from disk later using:
# model.load_weights('cnn.h5')

# Predict on the first 5 test images.
predictions = model.predict(test_images[:5])

# Print our model's predictions.
print(np.argmax(predictions, axis=1)) # [7, 2, 1, 0, 4]

# Check our predictions against the ground truths.
print(test_labels[:5]) # [7, 2, 1, 0, 4]

[7 2 1 0 4]
[7 2 1 0 4]


# Recommended Experiments

## 1. Varying network depth

In [7]:
# Build the model.
model = Sequential([
  Conv2D(num_filters, filter_size, input_shape=(28, 28, 1)),
  Conv2D(num_filters, filter_size), #Layer added
  MaxPooling2D(pool_size=pool_size),
  Flatten(),
  Dense(10, activation='softmax'),
])

# Compile the model.
model.compile(
  'adam',
  loss='categorical_crossentropy',
  metrics=['accuracy'],
)

# Train the model.
model.fit(
  train_images,
  to_categorical(train_labels),
  epochs=3,
  validation_data=(test_images, to_categorical(test_labels)),
)

Epoch 1/3
1875/1875 [==============================] - 38s 20ms/step - loss: 0.2644 - accuracy: 0.9216 - val_loss: 0.1153 - val_accuracy: 0.9650
Epoch 2/3
1875/1875 [==============================] - 33s 17ms/step - loss: 0.1094 - accuracy: 0.9679 - val_loss: 0.0885 - val_accuracy: 0.9727
Epoch 3/3
1875/1875 [==============================] - 30s 16ms/step - loss: 0.0834 - accuracy: 0.9751 - val_loss: 0.0878 - val_accuracy: 0.9714


In [9]:
# Save the model to disk.
model.save_weights('cnn2.h5')

# Load the model from disk later using:
# model.load_weights('cnn.h5')

# Predict on the first 5 test images.
predictions = model.predict(test_images[:20])

# Print our model's predictions.
print(np.argmax(predictions, axis=1))

# Check our predictions against the ground truths.
print(test_labels[:20])

[7 2 1 0 4 1 4 9 5 9 0 6 9 0 1 5 9 7 5 4]
[7 2 1 0 4 1 4 9 5 9 0 6 9 0 1 5 9 7 3 4]


## 2. Adding Dropout layers

In [10]:
# Build the model.
model = Sequential([
  Conv2D(num_filters, filter_size, input_shape=(28, 28, 1)),
  MaxPooling2D(pool_size=pool_size),
  Dropout(0.5), #Dropout layer
  Flatten(),
  Dense(10, activation='softmax'),
])

# Compile the model.
model.compile(
  'adam',
  loss='categorical_crossentropy',
  metrics=['accuracy'],
)

# Train the model.
model.fit(
  train_images,
  to_categorical(train_labels),
  epochs=3,
  validation_data=(test_images, to_categorical(test_labels)),
)

Epoch 1/3
1875/1875 [==============================] - 31s 16ms/step - loss: 0.4176 - accuracy: 0.8745 - val_loss: 0.2073 - val_accuracy: 0.9402
Epoch 2/3
1875/1875 [==============================] - 24s 13ms/step - loss: 0.2561 - accuracy: 0.9231 - val_loss: 0.1598 - val_accuracy: 0.9541
Epoch 3/3
1875/1875 [==============================] - 21s 11ms/step - loss: 0.2263 - accuracy: 0.9313 - val_loss: 0.1398 - val_accuracy: 0.9573


In [11]:
# Save the model to disk.
model.save_weights('cnn4_1.h5')

# Load the model from disk later using:
# model.load_weights('cnn.h5')

# Predict on the first 5 test images.
predictions = model.predict(test_images[:20])

# Print our model's predictions.
print(np.argmax(predictions, axis=1))

# Check our predictions against the ground truths.
print(test_labels[:20])

[7 2 1 0 4 1 4 9 6 9 0 6 9 0 1 5 9 7 3 4]
[7 2 1 0 4 1 4 9 5 9 0 6 9 0 1 5 9 7 3 4]


## 3. Adding Fully-connected Layers

In [12]:
# Build the model.
model = Sequential([
  Conv2D(num_filters, filter_size, input_shape=(28, 28, 1)),
  MaxPooling2D(pool_size=pool_size),
  Flatten(),
  Dense(64, activation='relu'), #Fully connected layer
  Dense(10, activation='softmax'),
])

# Compile the model.
model.compile(
  'adam',
  loss='categorical_crossentropy',
  metrics=['accuracy'],
)

# Train the model.
model.fit(
  train_images,
  to_categorical(train_labels),
  epochs=3,
  validation_data=(test_images, to_categorical(test_labels)),
)

Epoch 1/3
1875/1875 [==============================] - 26s 14ms/step - loss: 0.3063 - accuracy: 0.9107 - val_loss: 0.1557 - val_accuracy: 0.9532
Epoch 2/3
1875/1875 [==============================] - 20s 11ms/step - loss: 0.1133 - accuracy: 0.9668 - val_loss: 0.0865 - val_accuracy: 0.9747
Epoch 3/3
1875/1875 [==============================] - 19s 10ms/step - loss: 0.0757 - accuracy: 0.9773 - val_loss: 0.0714 - val_accuracy: 0.9774


In [13]:
# Save the model to disk.
model.save_weights('cnn4.h5')

# Load the model from disk later using:
# model.load_weights('cnn.h5')

# Predict on the first 5 test images.
predictions = model.predict(test_images[:20])

# Print our model's predictions.
print(np.argmax(predictions, axis=1))

# Check our predictions against the ground truths.
print(test_labels[:20])

[7 2 1 0 4 1 4 9 5 9 0 6 9 0 1 5 9 7 3 4]
[7 2 1 0 4 1 4 9 5 9 0 6 9 0 1 5 9 7 3 4]


## 4. Messing with convolution parameters 

In [17]:
# Build the model.
model = Sequential([
  Conv2D(
    num_filters,
    filter_size,
    input_shape=(28, 28, 1),
    strides=2,    padding='same',    activation='relu',  ), #Modified and added parameters
  MaxPooling2D(pool_size=pool_size),
  Flatten(),
  Dense(10, activation='softmax'),
])

# Compile the model.
model.compile(
  'adam',
  loss='categorical_crossentropy',
  metrics=['accuracy'],
)

# Train the model.
model.fit(
  train_images,
  to_categorical(train_labels),
  epochs=3,
  validation_data=(test_images, to_categorical(test_labels)),
)

Epoch 1/3
1875/1875 [==============================] - 14s 7ms/step - loss: 0.4573 - accuracy: 0.8768 - val_loss: 0.2127 - val_accuracy: 0.9374
Epoch 2/3
1875/1875 [==============================] - 12s 6ms/step - loss: 0.1933 - accuracy: 0.9424 - val_loss: 0.1611 - val_accuracy: 0.9517
Epoch 3/3
1875/1875 [==============================] - 11s 6ms/step - loss: 0.1574 - accuracy: 0.9525 - val_loss: 0.1436 - val_accuracy: 0.9587


In [18]:
# Save the model to disk.
model.save_weights('cnn2.h5')

# Load the model from disk later using:
# model.load_weights('cnn.h5')

# Predict on the first 5 test images.
predictions = model.predict(test_images[:20])

# Print our model's predictions.
print(np.argmax(predictions, axis=1))

# Check our predictions against the ground truths.
print(test_labels[:20])

[7 2 1 0 4 1 4 9 6 9 0 6 9 0 1 5 9 7 3 4]
[7 2 1 0 4 1 4 9 5 9 0 6 9 0 1 5 9 7 3 4]


# Personal experiments

In [14]:
# Build the model.
model = Sequential([
  Conv2D(
    num_filters,
    filter_size,
    input_shape=(28, 28, 1),
    strides=2,    padding='same',    activation='relu',  ), #Modified and added parameters
  Conv2D(num_filters, filter_size), #Layer added
    MaxPooling2D(pool_size=pool_size),
  Flatten(),
  Dense(64, activation='relu'), #Fully connected layer
  Dense(10, activation='softmax'),
])

# Compile the model.
model.compile(
  'adam',
  loss='categorical_crossentropy',
  metrics=['accuracy'],
)

# Train the model.
model.fit(
  train_images,
  to_categorical(train_labels),
  epochs=3,
  validation_data=(test_images, to_categorical(test_labels)),
)

Epoch 1/3
1875/1875 [==============================] - 21s 11ms/step - loss: 0.2564 - accuracy: 0.9219 - val_loss: 0.0948 - val_accuracy: 0.9685
Epoch 2/3
1875/1875 [==============================] - 19s 10ms/step - loss: 0.0775 - accuracy: 0.9758 - val_loss: 0.0600 - val_accuracy: 0.9799
Epoch 3/3
1875/1875 [==============================] - 19s 10ms/step - loss: 0.0558 - accuracy: 0.9830 - val_loss: 0.0507 - val_accuracy: 0.9830


In [15]:
# Save the model to disk.
model.save_weights('cnn5.h5')

# Load the model from disk later using:
# model.load_weights('cnn.h5')

# Predict on the first 5 test images.
predictions = model.predict(test_images[:20])

# Print our model's predictions.
print(np.argmax(predictions, axis=1))

# Check our predictions against the ground truths.
print(test_labels[:20])

[7 2 1 0 4 1 4 9 5 9 0 6 9 0 1 5 9 7 8 4]
[7 2 1 0 4 1 4 9 5 9 0 6 9 0 1 5 9 7 3 4]


## Experimento 2

In [35]:
train_images = mnist.train_images()
train_labels = mnist.train_labels()
test_images = mnist.test_images()
test_labels = mnist.test_labels()

In [38]:
# Normalize the images.
##train_images = (train_images / 255) - 0.5
##test_images = (test_images / 255) - 0.5

# Reshape the images.
##train_images = np.expand_dims(train_images, axis=3)
##test_images = np.expand_dims(test_images, axis=3)

num_filters = 8
filter_size = 3
pool_size = 2

In [37]:
# Build the model.
model = Sequential([
  Conv2D(
    num_filters,
    filter_size,
    input_shape=(28, 28, 1),
    strides=2,    padding='same',    activation='relu',  ), #Modified and added parameters
  Conv2D(num_filters, filter_size), #Layer added
  MaxPooling2D(pool_size=pool_size),
  Dropout(0.5), #Dropout layer
  Flatten(),
  Dense(64, activation='relu'), #Fully connected layer
  Dense(10, activation='softmax'),
])

# Compile the model.
model.compile(
  'adam',
  loss='categorical_crossentropy',
  metrics=['accuracy'],
)

# Train the model.
model.fit(
  train_images,
  to_categorical(train_labels),
  epochs=3,
  validation_data=(test_images, to_categorical(test_labels)),
)

Epoch 1/3
1875/1875 [==============================] - 27s 14ms/step - loss: 0.3988 - accuracy: 0.8747 - val_loss: 0.1094 - val_accuracy: 0.9650
Epoch 2/3
1875/1875 [==============================] - 21s 11ms/step - loss: 0.1740 - accuracy: 0.9455 - val_loss: 0.0741 - val_accuracy: 0.9762
Epoch 3/3
1875/1875 [==============================] - 20s 11ms/step - loss: 0.1381 - accuracy: 0.9573 - val_loss: 0.0589 - val_accuracy: 0.9821


In [39]:
# Save the model to disk.
model.save_weights('cnn6.h5')

# Load the model from disk later using:
# model.load_weights('cnn.h5')

# Predict on the first 5 test images.
predictions = model.predict(test_images[:20])

# Print our model's predictions.
print(np.argmax(predictions, axis=1))

# Check our predictions against the ground truths.
print(test_labels[:20])

[7 2 1 0 4 1 4 9 5 9 0 6 9 0 1 5 9 7 5 4]
[7 2 1 0 4 1 4 9 5 9 0 6 9 0 1 5 9 7 3 4]


## Experimento 3
Adding one more filter (num_filters)

In [40]:
# Normalize the images.
#train_images = (train_images / 255) - 0.5
#test_images = (test_images / 255) - 0.5

# Reshape the images.
##train_images = np.expand_dims(train_images, axis=3)
##test_images = np.expand_dims(test_images, axis=3)

num_filters = 9
filter_size = 3
pool_size = 2

In [41]:
# Build the model.
model = Sequential([
  Conv2D(
    num_filters,
    filter_size,
    input_shape=(28, 28, 1),
    strides=2,    padding='same',    activation='relu',  ), #Modified and added parameters
  Conv2D(num_filters, filter_size), #Layer added
  MaxPooling2D(pool_size=pool_size),
  Dropout(0.5), #Dropout layer
  Flatten(),
  Dense(64, activation='relu'), #Fully connected layer
  Dense(10, activation='softmax'),
])

# Compile the model.
model.compile(
  'adam',
  loss='categorical_crossentropy',
  metrics=['accuracy'],
)

# Train the model.
model.fit(
  train_images,
  to_categorical(train_labels),
  epochs=3,
  validation_data=(test_images, to_categorical(test_labels)),
)

Epoch 1/3
1875/1875 [==============================] - 22s 12ms/step - loss: 0.3726 - accuracy: 0.8812 - val_loss: 0.0984 - val_accuracy: 0.9697
Epoch 2/3
1875/1875 [==============================] - 23s 12ms/step - loss: 0.1668 - accuracy: 0.9469 - val_loss: 0.0681 - val_accuracy: 0.9771
Epoch 3/3
1875/1875 [==============================] - 19s 10ms/step - loss: 0.1308 - accuracy: 0.9595 - val_loss: 0.0530 - val_accuracy: 0.9822


In [42]:
# Save the model to disk.
model.save_weights('cnn7.h5')

# Load the model from disk later using:
# model.load_weights('cnn.h5')

# Predict on the first 5 test images.
predictions = model.predict(test_images[:20])

# Print our model's predictions.
print(np.argmax(predictions, axis=1))

# Check our predictions against the ground truths.
print(test_labels[:20])

[7 2 1 0 4 1 4 9 5 9 0 6 9 0 1 5 9 7 5 4]
[7 2 1 0 4 1 4 9 5 9 0 6 9 0 1 5 9 7 3 4]


## Experimento 4
Adding 3 more filter (num_filters=12)

filter_size and pool size not modified because we think those sizes are perfect since their objective is to detect image features.

In [43]:
# Normalize the images.
#train_images = (train_images / 255) - 0.5
#test_images = (test_images / 255) - 0.5

# Reshape the images.
##train_images = np.expand_dims(train_images, axis=3)
##test_images = np.expand_dims(test_images, axis=3)

num_filters = 12
filter_size = 3
pool_size = 2

In [44]:
# Build the model.
model = Sequential([
  Conv2D(
    num_filters,
    filter_size,
    input_shape=(28, 28, 1),
    strides=2,    padding='same',    activation='relu',  ), #Modified and added parameters
  Conv2D(num_filters, filter_size), #Layer added
  MaxPooling2D(pool_size=pool_size),
  Dropout(0.5), #Dropout layer
  Flatten(),
  Dense(64, activation='relu'), #Fully connected layer
  Dense(10, activation='softmax'),
])

# Compile the model.
model.compile(
  'adam',
  loss='categorical_crossentropy',
  metrics=['accuracy'],
)

# Train the model.
model.fit(
  train_images,
  to_categorical(train_labels),
  epochs=3,
  validation_data=(test_images, to_categorical(test_labels)),
)

Epoch 1/3
1875/1875 [==============================] - 21s 11ms/step - loss: 0.3467 - accuracy: 0.8903 - val_loss: 0.0769 - val_accuracy: 0.9754
Epoch 2/3
1875/1875 [==============================] - 24s 13ms/step - loss: 0.1315 - accuracy: 0.9594 - val_loss: 0.0566 - val_accuracy: 0.9809
Epoch 3/3
1875/1875 [==============================] - 19s 10ms/step - loss: 0.1032 - accuracy: 0.9678 - val_loss: 0.0435 - val_accuracy: 0.9851


In [45]:
# Save the model to disk.
model.save_weights('cnn8.h5')

# Load the model from disk later using:
# model.load_weights('cnn.h5')

# Predict on the first 5 test images.
predictions = model.predict(test_images[:20])

# Print our model's predictions.
print(np.argmax(predictions, axis=1))

# Check our predictions against the ground truths.
print(test_labels[:20])

[7 2 1 0 4 1 4 9 5 9 0 6 9 0 1 5 9 7 3 4]
[7 2 1 0 4 1 4 9 5 9 0 6 9 0 1 5 9 7 3 4]


## Experimento 5
filter_size and pool size not modified because we think those sizes are perfect since their objective is to detect image features.

Incremented epochs to 10.

We also added another con2D layer.

We also changed loss function to 'binary crossentropy'.

In [46]:
# Normalize the images.
#train_images = (train_images / 255) - 0.5
#test_images = (test_images / 255) - 0.5

# Reshape the images.
##train_images = np.expand_dims(train_images, axis=3)
##test_images = np.expand_dims(test_images, axis=3)

num_filters = 12
filter_size = 3
pool_size = 2

In [47]:
# Build the model.
model = Sequential([
  Conv2D(
    num_filters,
    filter_size,
    input_shape=(28, 28, 1),
    strides=2,    padding='same',    activation='relu',  ), #Modified and added parameters
  Conv2D(num_filters, filter_size), #Layer added
  Conv2D(num_filters, filter_size), #Layer added
  MaxPooling2D(pool_size=pool_size),
  Dropout(0.5), #Dropout layer
  Flatten(),
  Dense(64, activation='relu'), #Fully connected layer
  Dense(10, activation='softmax'),
])

# Compile the model.
model.compile(
  'adam',
  loss='binary_crossentropy',
  metrics=['accuracy'],
)

# Train the model.
model.fit(
  train_images,
  to_categorical(train_labels),
  epochs=10,
  validation_data=(test_images, to_categorical(test_labels)),
)

Epoch 1/10
1875/1875 [==============================] - 32s 17ms/step - loss: 0.0525 - accuracy: 0.9002 - val_loss: 0.0156 - val_accuracy: 0.9721
Epoch 2/10
1875/1875 [==============================] - 25s 13ms/step - loss: 0.0245 - accuracy: 0.9574 - val_loss: 0.0110 - val_accuracy: 0.9805
Epoch 3/10
1875/1875 [==============================] - 33s 18ms/step - loss: 0.0197 - accuracy: 0.9655 - val_loss: 0.0099 - val_accuracy: 0.9823
Epoch 4/10
1875/1875 [==============================] - 37s 20ms/step - loss: 0.0168 - accuracy: 0.9705 - val_loss: 0.0079 - val_accuracy: 0.9866
Epoch 5/10
1875/1875 [==============================] - 28s 15ms/step - loss: 0.0153 - accuracy: 0.9734 - val_loss: 0.0074 - val_accuracy: 0.9876
Epoch 6/10
1875/1875 [==============================] - 31s 17ms/step - loss: 0.0138 - accuracy: 0.9764 - val_loss: 0.0069 - val_accuracy: 0.9888
Epoch 7/10
1875/1875 [==============================] - 29s 16ms/step - loss: 0.0130 - accuracy: 0.9773 - val_loss: 0.0070 -

In [48]:
# Save the model to disk.
model.save_weights('cnn9.h5')

# Load the model from disk later using:
# model.load_weights('cnn.h5')

# Predict on the first 5 test images.
predictions = model.predict(test_images[:20])

# Print our model's predictions.
print(np.argmax(predictions, axis=1))

# Check our predictions against the ground truths.
print(test_labels[:20])

[7 2 1 0 4 1 4 9 5 9 0 6 9 0 1 5 9 7 8 4]
[7 2 1 0 4 1 4 9 5 9 0 6 9 0 1 5 9 7 3 4]


In [50]:
import tensorflow

In [51]:
tensorflow.keras.losses.MeanSquaredError(reduction="auto", name="mean_squared_error")

## Experimento 6

Same as experiment 5, but we changed the loss function back to 'categorical crossentropy'.

In [52]:
# Normalize the images.
#train_images = (train_images / 255) - 0.5
#test_images = (test_images / 255) - 0.5

# Reshape the images.
##train_images = np.expand_dims(train_images, axis=3)
##test_images = np.expand_dims(test_images, axis=3)

num_filters = 12
filter_size = 3
pool_size = 2

In [53]:
# Build the model.
model = Sequential([
  Conv2D(
    num_filters,
    filter_size,
    input_shape=(28, 28, 1),
    strides=2,    padding='same',    activation='relu',  ), #Modified and added parameters
  Conv2D(num_filters, filter_size), #Layer added
  Conv2D(num_filters, filter_size), #Layer added
  MaxPooling2D(pool_size=pool_size),
  Dropout(0.5), #Dropout layer
  Flatten(),
  Dense(64, activation='relu'), #Fully connected layer
  Dense(10, activation='softmax'),
])

# Compile the model.
model.compile(
  'adam',
  loss='categorical_crossentropy',
  metrics=['accuracy'],
)

# Train the model.
model.fit(
  train_images,
  to_categorical(train_labels),
  epochs=10,
  validation_data=(test_images, to_categorical(test_labels)),
)

Epoch 1/10
1875/1875 [==============================] - 27s 14ms/step - loss: 0.3107 - accuracy: 0.9018 - val_loss: 0.0756 - val_accuracy: 0.9770
Epoch 2/10
1875/1875 [==============================] - 32s 17ms/step - loss: 0.1343 - accuracy: 0.9578 - val_loss: 0.0526 - val_accuracy: 0.9836
Epoch 3/10
1875/1875 [==============================] - 23s 13ms/step - loss: 0.1037 - accuracy: 0.9672 - val_loss: 0.0424 - val_accuracy: 0.9875
Epoch 4/10
1875/1875 [==============================] - 24s 13ms/step - loss: 0.0847 - accuracy: 0.9727 - val_loss: 0.0396 - val_accuracy: 0.9875
Epoch 5/10
1875/1875 [==============================] - 23s 12ms/step - loss: 0.0745 - accuracy: 0.9767 - val_loss: 0.0350 - val_accuracy: 0.9888
Epoch 6/10
1875/1875 [==============================] - 32s 17ms/step - loss: 0.0701 - accuracy: 0.9778 - val_loss: 0.0299 - val_accuracy: 0.9906
Epoch 7/10
1875/1875 [==============================] - 23s 12ms/step - loss: 0.0645 - accuracy: 0.9797 - val_loss: 0.0312 -

In [54]:
# Save the model to disk.
model.save_weights('cnn10.h5')

# Load the model from disk later using:
# model.load_weights('cnn.h5')

# Predict on the first 5 test images.
predictions = model.predict(test_images[:20])

# Print our model's predictions.
print(np.argmax(predictions, axis=1))

# Check our predictions against the ground truths.
print(test_labels[:20])

[7 2 1 0 4 1 4 9 5 9 0 6 9 0 1 5 9 7 3 4]
[7 2 1 0 4 1 4 9 5 9 0 6 9 0 1 5 9 7 3 4]
